version: 0.2
env:
  variables:
    DOTNET_ROOT: /root/.dotnet
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - echo Restore started on `date`
      - export CBN=$CODEBUILD_BUILD_NUMBER
  build:
    commands:
      - echo Build started on `date`
